export const ADD_DISHES = "ADD_DISHES";
export const LOADING_DISHES = "LOADING_DISHES";
export const FAILLOADING_DISHES = "FAILLOADING_DISHES"

export const ADD_COMMENT = "ADD_COMMENT"
export const ADD_COMMENTS = "ADD_COMMENTS";
export const FAILLOADING_COMMENTS = "FAILLOADING_COMMENTS"

export const ADD_PROMOS = "ADD_PROMOS"
export const LOADING_PROMOS = "LOADING_PROMOS"
export const FAILLOADING_PROMOS = "FAILLOADING_PROMOS"